clipable/clipable

- frontend/src/app/page.tsx
- frontend/src/shared/api.ts
Adds cards that indicate when a video is still processing.
Done with the aim of telling a user that his video is still processing and hasnt dissapeared/not gone through.
> Indication on card to show that video is still processing

- frontend/src/app/page.tsx
- frontend/src/context/user-context.tsx
- frontend/src/shared/api.ts
- frontend/src/shared/date-formatter.ts
- frontend/src/shared/video-card.tsx
- frontend/src/shared/views-formatter.ts
- frontend/src/types/user.ts
- Adds a general `VideoCard` component to be used across components
- Adjusts naming of API types
- Removes `types/user` in favor of `api/user`
> Add a VideoCard component and general cleanup

- backend/modelsx/querybuilder.go
- backend/routes/routes.go
- backend/routes/users.go
- Adds a `QueryBuilder` to add multiple queries together for SQLBoiler, thanks @ImVexed !
- Adds a new route to get the current users clips
> Add route to get current users clips

- .github/workflows/images.yml
- .github/workflows/merge.yml
- backend/go.mod
- backend/go.sum
- backend/routes/dash.go
- backend/routes/dash_test.go
- backend/routes/internal.go
- backend/routes/internal_test.go
- backend/routes/users_test.go
- backend/services/interfaces.go
- backend/services/mock/interfaces.go
- Adds test coverage for `routes/users.go` `routes/internal.go` `routes/dash.go` 
- Adds a new ci workflow for testing the backend in PRs
> Backend Tests

- backend/routes/dash.go
- backend/routes/middleware.go
- backend/routes/routes.go
- backend/server/server.go
Dynamically assigns read/write timeout based on how long it would take to transfer over a 500Kbps connection.
> adds dynamic timeouts

- backend/services/db/clip.go
This is something I didn't realize we we're missing as all the `modelsx` code was already in place, so I've added the few database mods we weren't including so every clip object that is returned by the API also includes an embedded `creator` field.
This unblocks the completion of https://github.com/clipable/clipable/issues/61 and will have to have a frontend follow up pr for https://github.com/clipable/clipable/pull/74
> add in eager loading for creator

- frontend/src/shared/video-card.tsx
User account page was completed before but we finally linked to it now.
Closes https://github.com/clipable/clipable/issues/4#issue-1575616768
Added video author name to the gallery tile view and for the clips themselves.
Closes https://github.com/clipable/clipable/issues/61#issue-1588904893
Added a link to the authors name that brings you to their page so you can see what else they uploaded. 
Closes https://github.com/clipable/clipable/issues/79#issue-1597632074
> Added creator to video card, added link to video creators uploads page

- README.md
Closes https://github.com/clipable/clipable/issues/46
Also Closes https://github.com/clipable/clipable/issues/14
> Add docker install steps

- frontend/src/app/clips/[id]/page.tsx
- frontend/src/app/header.tsx
The title size previously was very small and bold, causing the font to look very strange:
Now it lookslike:
> fix title size

- frontend/src/app/header.tsx
- frontend/src/app/page.tsx
- frontend/src/shared/api.ts
> Add support for searching videos

- backend/routes/dash.go
- backend/routes/dash_test.go
- backend/routes/internal.go
- backend/services/interfaces.go
- backend/services/mock/interfaces.go
- backend/services/object/store.go
closes https://github.com/clipable/clipable/issues/102
> support etags

- frontend/src/app/clips/[id]/page.tsx
This adds the player's volume to local storage and will initialize the player with that volume. This is so your volume adjustments are saved and applied across various videos.
closes #73
> Add volume to local storage

- frontend/src/app/page.tsx
> Fix video cards overlapping

- Dockerfile
- backend/config/config.go
- backend/migrations/000003_add_unlisted_to_clips_table.down.sql
- backend/migrations/000003_add_unlisted_to_clips_table.up.sql
- backend/models/clips.go
- backend/modelsx/clip.go
- backend/modelsx/querybuilder.go
- backend/routes/auth.go
- backend/routes/clips.go
- backend/routes/internal.go
- backend/routes/middleware.go
- backend/routes/routes.go
- backend/routes/users.go
- backend/routes/users_test.go
- backend/server/server.go
- backend/services/db/clip.go
- backend/services/interfaces.go
- backend/services/mock/interfaces.go
- backend/services/transcoder/resolution.go
- backend/services/transcoder/transcoder.go
- docker-compose.yml
- frontend/src/app/clips/[id]/page.tsx
- frontend/src/app/page.tsx
- frontend/src/app/upload/page.tsx
- frontend/src/app/users/[id]/page.tsx
- frontend/src/shared/api.ts
- frontend/src/shared/clip-card-image.tsx
- frontend/src/shared/clip-card.tsx
> Add support for unlisted videos

- backend/routes/clips.go
- backend/server/server.go
- backend/services/db/clip.go
- backend/services/transcoder/transcoder.go
- frontend/src/app/page.tsx
- frontend/src/app/upload/page.tsx
- Adds a new progress value, -2, that represents a clip has failed to transcode
- Deletes a given clip if it fails to transcode
- Adds more detailed logging when we do fail to transcode
- Adds frontend handling for a transcode failure
Closes https://github.com/clipable/clipable/issues/94
> handle clips failing to transcode

- frontend/src/app/upload/page.tsx
> Switch to using a textarea on the upload page

- backend/config/config.go
- backend/routes/auth.go
- backend/routes/routes.go
- backend/services/transcoder/resolution.go
- docker-compose.yml
- frontend/next.config.js
- frontend/src/app/login/page.tsx
- frontend/src/app/register/page.tsx
- frontend/src/shared/api.ts
closes https://github.com/clipable/clipable/issues/130
> conditionally allow registration

- backend/modelsx/clip.go
- backend/routes/clips.go
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/public/trashcan.svg
- frontend/src/app/clips/[id]/page.tsx
- frontend/src/app/page.tsx
- frontend/src/shared/api.ts
- frontend/src/shared/modal.tsx
- frontend/src/shared/use-click-outside.ts
> Add modals for editing and deleting clips

- frontend/src/app/clips/[id]/page.tsx
Closes https://github.com/clipable/clipable/issues/142
Closes https://github.com/clipable/clipable/issues/141
Re-orders our buttons, and remove language from overflow menu
> reorder player buttons

- frontend/src/app/upload/page.tsx
Closes https://github.com/clipable/clipable/issues/85
> Added progress smoothing to upload page

- .github/workflows/images.yml
- backend/config/config.go
- backend/modelsx/clip.go
- backend/modelsx/user.go
- backend/routes/routes.go
- backend/server/server.go
- backend/services/db/clip.go
- backend/services/transcoder/resolution.go
- backend/services/transcoder/transcoder.go
- docker-compose.yml
- gpu.Dockerfile
- gpu.docker-compose.yml
- Closes https://github.com/clipable/clipable/issues/13
- Closes https://github.com/clipable/clipable/issues/152
- Adds gpu.Dockerfile for building a version of Clipable with nvenc support
- Adds gpu.docker-compose.yml for starting clipable with nvenc support
- Also added a wiki page with more details https://github.com/clipable/clipable/wiki/FFmpeg-GPU-Support  
This isn't *full* GPU support, the CPU is still doing all the `filter_complex` rules to resize the frames and add black bars. We could try to add GPU support for this, but, it would be much more work as pretty much none of syntax for the environment variables transfers.
> GPU Support
